### ISSUE TITLE
Variadic operator

### ISSUE THREAD

**Issue by lgarithm** [lgarithm/crystalnet#62]
A **variadic** operator is an operator that takes a varied number of arguments.
variadic operator is an extension to #23 

examples of variadic operators are
* merge/concat
*

**Comment by lgarithm** [comment]
Alternatively, we can define one operator for each arity.

**Comment by luomai** [comment]
emm, how many operators we would need for covering each arity demanded by Yolo?

**Comment by lgarithm** [comment]
only 2, 
route_1, and route_2
